name : ci and cd pipeline

on:
    push:
        branch: main
    pull request:
        branch: main

    
    build:
        runs on: ubuntu-latest
        jobs:
            - name: checkout code
              uses: actions/checkout@v6

            - name: Build and push
              uses: docker/build-push-action@v6
                    run dockerbuild -t githubgist .
            
            - name: run container
               docker run githubgist -p 8080:8080            
                



