name : ci and cd pipeline

on:
    push:
        branch: main
    pull request:
        branch: main

    
    build:
        runs on: ubuntu-latest
        jobs:
            - name: checkout code
                uses: actions/checkout@v6

            - name: docker build
                uses: docker/setup-buildx-action@v3
                run dockerbuild -t githubgist .
            
            - name: run container
               docker run githubgist -p 8080:8080
               
            - name: install python
                



